# Generated by Django 4.2.23 on 2025-11-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, default='2000-01-01', null=True)),
                ('password', models.CharField(default=123, max_length=128)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('speciality', models.CharField(blank=True, choices=[('beginer', 'Beginer Trainer'), ('intermediate', 'Intermediate Trainer'), ('professional', 'Professional Trainer'), ('liveguard', 'Lifeguard Trainer'), ('diver', 'Diver Trainer')], max_length=15, null=True)),
                ('time_slot', models.CharField(choices=[('slot1', '6AM - 8AM'), ('slot2', '8AM - 10AM'), ('slot3', '4PM - 6PM'), ('slot4', '6PM - 8PM')], max_length=10)),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('adhaar_no', models.CharField(blank=True, max_length=12, null=True, unique=True)),
            ],
        ),
    ]
