# Generated by Django 4.2.23 on 2025-11-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myuser',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('dob', models.DateField(blank=True, default='2000-01-01', null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True)),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('adhaar_no', models.CharField(blank=True, max_length=12, null=True, unique=True)),
            ],
        ),
    ]
