# Generated by Django 4.2.23 on 2025-11-17 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('dob', models.DateField(default='2000-01-01')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('time_slot', models.CharField(choices=[('slot1', '6AM - 8AM'), ('slot2', '8AM - 10AM'), ('slot3', '4PM - 6PM'), ('slot4', '6PM - 8PM')], max_length=10)),
                ('plan', models.CharField(choices=[('basic', '2000'), ('priminum', '3000'), ('elite', '5000'), ('family', '6000')], default='basic', max_length=10)),
                ('start_data', models.DateField(auto_now=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('u_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.myuser')),
            ],
        ),
    ]
